#!/usr/bin/env bash
# Transfers a file from client to a server using scp

if [ $# -ne 4 ];
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	path_to_file=$1
	ip=$2
	username=$3
	ssh_key=$4
	
	scp -o StrictHostKeyChecking=no -i "${ssh_key}" "${path_to_file}" "${username}"@"${ip}":'~/'
fi
