#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo service nginx start

echo "Hello World!" > /var/www/html/index.nginx-debian.html

line="\\\trewrite ^/redirect_me https://www.linkedin.com/in/michael-oyedepo permanent;"

sudo sed -i "26i $line" /etc/nginx/sites-available/default

sudo service nginx restart

# Wait for NGINX to restart
sleep 2

# Check NGINX status
if ps ax | pgrep -v nginx >/dev/null; then                          echo "NGINX is running."
else
    echo "NGINX is not running."
fi
