#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

line="\\\trewrite ^/redirect_me https://www.linkedin.com/in/michael-oyedepo permanent;"

sudo sed -i "26i $line" /etc/nginx/sites-available/default

sudo service nginx restart

# Wait for NGINX to restart
sleep 2

# Check NGINX status
if ps ax | pgrep -v nginx >/dev/null; then                          echo "NGINX is running."
else
    echo "NGINX is not running."
fi
