#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page

echo "Ceci n'est pas une page" > 404_custom.html

cp 404_custom.html /var/www/html/

# Define the custom error page configuration
error_page_config='    error_page 404 /404_custom.html;\n\n    location = /404_custom.html {\n        internal;\n        root /var/www/html;\n   }\n'

# Add the custom error page configuration to the Nginx configuration file
sed -i "/http {/a $error_page_config" /etc/nginx/nginx.conf

# Reload NGINX configuration without systemctl
killall -s HUP nginx                                            

# Wait for NGINX to restart
sleep 2

# Check NGINX status
if ps ax | pgrep -v nginx >/dev/null; then
	echo "NGINX is running."
else
    echo "NGINX is not running."
fi
