#!/usr/bin/env bash
# Install nginx web server on my server

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

mkdir -p /var/www/mypage.com/html

echo "Hello World!" > /var/www/html/index.nginx-debian.html


# Reload NGINX configuration without systemctl
sudo service nginx restart

# Wait for NGINX to restart
sleep 2

# Check NGINX status
if ps ax | pgrep -v nginx >/dev/null; then
    echo "NGINX is running."
else
    echo "NGINX is not running."
fi
