#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
# So that it sends traffic to web-01 and web-02

echo "##########"
echo "# Updating and installing packages"
echo "##########"

sudo apt update && sudo apt upgrade -y

echo "##########"
echo "# Installing HAproxy"
echo "##########"

sudo apt install -y haproxy

echo "##########"
echo "# Configuring HAproxy (backing up original)"
echo "##########"

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

echo "##########"
echo "# Configuring Frontend"
echo "##########"

cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend haproxy-main
    bind *:80
    default_backend nginx_webservers
EOF

echo "##########"
echo "# Configuring Backend"
echo "##########"

cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg
backend nginx_webservers
    balance roundrobin
    server 221967-web-01  100.26.216.42:80 check
    server 221967-web-02  54.84.238.169:80 check
EOF

echo "##########"
echo "# Enabling init"
echo "##########"

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "##########"
echo "# Restarting HAproxy server"
echo "##########"

sudo service haproxy restart

sleep 2

echo "##########"

if [[ $(systemctl status haproxy.service | grep 'active (running)') ]]; then
        echo "HAproxy restarted successfully"
        echo "########################"
        echo "##### Done #####"
else
        echo "Error restarting HAproxy"
fi
