#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server                                                      # So that it sends traffic to web-01 and web-02

echo "##########"
echo "# Updating and installing packages"
echo "##########"

sudo apt update && sudo apt upgrade -y

echo "##########"
echo "# Installing HAproxy"
echo "##########"

sudo apt install -y --no-install-recommends software-properties-common
echo | sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt update
sudo apt install -y haproxy=2.8.\*

echo "##########"
echo "# Configuring HAproxy (backing up original)"
echo "##########"

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

echo "##########"
echo "# Configuring Frontend"
echo "##########"

cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend nginx_webservers
EOF

echo "##########"
echo "# Configuring Backend"
echo "##########"

cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg
backend nginx_webservers
    balance roundrobin
    server web-01  100.26.216.42:80 check
    server web-02  54.84.238.169:80 check
EOF

echo "##########"
echo "# Restarting HAproxy server"
echo "##########"

sudo service haproxy restart

sleep 2

echo "##########"

if [[ $(systemctl status haproxy.service | grep 'active (running)') ]]; then
        echo "HAproxy restarted successfully"
        echo "########################"
        echo "##### Done #####"
else
        echo "Error restarting HAproxy"
fi
