#!/usr/bin/env bash
# uses ssh to connect to your server using the private key

if [ "$#" -ne 1 ];
then
	echo "Usage: $0 server_ip"
	exit 1
fi

ssh -i ~/.ssh/school ubuntu@"$1"

if [ $? -ne 0 ]; then
	echo "Failed to connect to the server."
	exit 1
fi
