#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

if [ $# -ne 1 ]; then
	echo "Usage: $0 <yourmysqlpassword>"
	exit 1
fi

sudo mysqldump -u root -p"$1" --all-databases > backup.sql

if [ $? -ne 0 ]; then
	echo "MySQL dump failed. Please check your password and try again."
	exit 1
fi

if [ -f backup.sql ]; then
	tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
fi
