#!/usr/bin/env bash
# the script displays Best School 10 times
# but Hi on the 9th interation 

count=0
while [ $count -lt 10 ];do
	if [ "$count" -eq 8 ];
	then
		echo Best School
		echo Hi
	else
		echo Best School
	fi
	((count++))
done
