#!/usr/bin/env bash
# the script displays Best School 10 times.
# displays "bad luck" on 4th interation and
#+ good luck on 8th interation

count=0
while [ $count -lt 10 ];do
	if [ "$count" -eq 3 ];
	then
		echo bad luck
	elif [ "$count" -eq 7 ]
	then
		echo good luck
	else
		echo Best School
	fi

	((count++))
done
