#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
useradd -r -s /sbin/nologin nginx
chown -R nginx:nginx /usr/sbin/nginx /etc/nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 0.0.0.0:8080;/' /etc/nginx/nginx.conf
service nginx restart
