#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sed -i 's/^user\s*.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
